name: myapp
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0-209.1.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  fl_chart: ^0.70.2
  rive: ^0.13.20
  file_picker: ^9.0.2
  google_maps_flutter: ^2.10.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  intl: ^0.20.2
  video_player: ^2.9.3
  flutter_sound: ^9.25.9
  permission_handler: ^11.4.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add the assets folder and the video file
  assets:
    - assets/video.mp4
